"""
Issue taxonomy — every flag raised by the firewall is one of these.
Strict tag system makes the output operational, measurable, and trainable.
"""

from __future__ import annotations
from enum import Enum


class IssueCategory(str, Enum):
    MISSING_CONTEXT = "MISSING_CONTEXT"
    CONTEXT_DRIFT = "CONTEXT_DRIFT"
    INVENTED_CONTEXT = "INVENTED_CONTEXT"
    COMPETITOR_PROMOTION = "COMPETITOR_PROMOTION"
    UNAUTHORIZED_BRAND_MENTION = "UNAUTHORIZED_BRAND_MENTION"
    BRAND_DILUTION = "BRAND_DILUTION"
    AI_SLOP = "AI_SLOP"
    ROBOTIC_TRANSITION = "ROBOTIC_TRANSITION"
    EMPTY_ABSTRACTION = "EMPTY_ABSTRACTION"
    GENERIC_FRAMEWORK = "GENERIC_FRAMEWORK"
    SEMANTIC_REPETITION = "SEMANTIC_REPETITION"
    TEMPLATE_RESIDUE = "TEMPLATE_RESIDUE"
    LOGICAL_GAP = "LOGICAL_GAP"
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    INTERNAL_CONTRADICTION = "INTERNAL_CONTRADICTION"
    FACTUAL_RISK = "FACTUAL_RISK"
    CAUSAL_JUMP = "CAUSAL_JUMP"
    TONE_MISMATCH = "TONE_MISMATCH"
    READER_INTENT_MISMATCH = "READER_INTENT_MISMATCH"
    SEO_IRRELEVANT_SECTION = "SEO_IRRELEVANT_SECTION"
    WEAK_EXAMPLE = "WEAK_EXAMPLE"
    NO_POINT_OF_VIEW = "NO_POINT_OF_VIEW"
    REDUNDANT_PARAGRAPH = "REDUNDANT_PARAGRAPH"
    HEADING_HIERARCHY_BROKEN = "HEADING_HIERARCHY_BROKEN"
    WEAK_INTRO = "WEAK_INTRO"
    DEAD_CONCLUSION = "DEAD_CONCLUSION"
    LIST_BLOAT = "LIST_BLOAT"
    KEYWORD_STUFFING = "KEYWORD_STUFFING"
    FAQ_IRRELEVANCE = "FAQ_IRRELEVANCE"
    OVERLONG_PARAGRAPH = "OVERLONG_PARAGRAPH"
    ABRUPT_TRANSITION = "ABRUPT_TRANSITION"
    FALSE_COMPARISON = "FALSE_COMPARISON"
    VAGUE_PRONOUN = "VAGUE_PRONOUN"
    UNDEFINED_TERM = "UNDEFINED_TERM"


class Severity(str, Enum):
    BLOCKER = "blocker"
    MAJOR = "major"
    MINOR = "minor"
    STYLE = "style"


class PublishDecision(str, Enum):
    PASS = "pass"
    PASS_WITH_REVISIONS = "pass_with_revisions"
    FAIL = "fail"


BLOCKER_CATEGORIES = {
    IssueCategory.COMPETITOR_PROMOTION,
    IssueCategory.UNAUTHORIZED_BRAND_MENTION,
    IssueCategory.FACTUAL_RISK,
    IssueCategory.INTERNAL_CONTRADICTION,
    IssueCategory.INVENTED_CONTEXT,
}

SEVERITY_WEIGHT = {
    Severity.BLOCKER: 10,
    Severity.MAJOR: 4,
    Severity.MINOR: 1,
    Severity.STYLE: 0.25,
}
